# Generated by Django 5.1.7 on 2026-02-07 19:54

import datetime
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "issue_date",
                    models.DateField(auto_now_add=True, verbose_name="Issue Date"),
                ),
                ("expiry_date", models.DateField(verbose_name="Expiry Date")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="License Qty"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "license_key",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        unique=True,
                        verbose_name="License Key",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "License",
                "verbose_name_plural": "Licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("RENEW", "Renew"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LicenseRenewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("renewal_date", models.DateField(auto_now_add=True)),
                (
                    "expiration_date",
                    models.DateField(default=datetime.date(2026, 3, 7)),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "License Renewal",
                "verbose_name_plural": "License Renewals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("coverage", models.TextField(blank=True, null=True)),
                ("sub_name", models.CharField(blank=True, max_length=150, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("duration", models.IntegerField(default=0)),
                ("max_users", models.PositiveIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "License Type",
                "verbose_name_plural": "License Types",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                ("schema_name", models.CharField(max_length=63, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("org_slug", models.SlugField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="tenant_logo/tenant_logo.png",
                        null=True,
                        upload_to="tenant/logo",
                        verbose_name="Tenant Logo",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Tenant Email"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "tenant",
                "verbose_name_plural": "tenant",
                "ordering": ["-created_at"],
            },
        ),
    ]
