# Generated by Django 5.1.7 on 2026-02-07 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_licenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users",
            ),
        ),
        migrations.AddField(
            model_name="licensehistory",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="client.license",
            ),
        ),
        migrations.AddField(
            model_name="licenserenewal",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="renewals",
                to="client.license",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="license_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="client.licensetype",
            ),
        ),
        migrations.AddField(
            model_name="licensehistory",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_history",
                to="client.tenant",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="client.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="license",
            constraint=models.UniqueConstraint(
                fields=("license_key", "tenant"), name="unique_license_key_per_tenant"
            ),
        ),
    ]
