# Generated by Django 5.1.7 on 2026-02-20 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_licenserenewal_expiration_date_refreshtoken_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenserenewal",
            name="expiration_date",
            field=models.DateField(default=datetime.date(2026, 3, 20)),
        ),
    ]
