# Generated by Django 5.1.7 on 2026-03-16 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_alter_licenserenewal_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenserenewal",
            name="expiration_date",
            field=models.DateField(default=datetime.date(2026, 4, 16)),
        ),
    ]
