# Generated by Django 5.1.7 on 2026-02-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userratelimitflag",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userratelimitflag",
            name="user",
        ),
        migrations.AddField(
            model_name="usergroup",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name="RefreshToken",
        ),
        migrations.DeleteModel(
            name="UserRateLimitFlag",
        ),
    ]
